<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Common.Extensions</AssemblyName>
        <RootNamespace>Common</RootNamespace>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.aspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" Version="9.0.3" />
    </ItemGroup>

</Project>
