<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Gateway.Telegram</AssemblyName>
        <RootNamespace>Gateway</RootNamespace>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Telegram.Bot" Version="22.5.0-dev.24" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Extensions\Extensions.csproj" />
    </ItemGroup>

</Project>
