version: "3.8"

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    secrets:
      - secrets_json
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}