version: "3.8"

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    secrets:
      - secrets_json
    volumes:
      - ./Gateway/secrets.json:/Gateway/secrets.json

secrets:
  secrets_json:
    external: true