<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Orleans.Silo</AssemblyName>
        <RootNamespace>Orleans</RootNamespace>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql" Version="9.0.0"/>
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="9.1.2" />
        <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="9.0.1"/>
        <PackageReference Include="Microsoft.Orleans.Server" Version="9.0.1"/>
        <PackageReference Include="Microsoft.Orleans.Streaming" Version="9.0.1"/>
        <PackageReference Include="Microsoft.Orleans.Transactions" Version="9.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj" />
      <ProjectReference Include="..\..\Common\Extensions\Extensions.csproj" />
      <ProjectReference Include="..\..\Users\Grains\Grains.csproj" />
      <ProjectReference Include="..\..\Users\Interfaces\Interfaces.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
