<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Metrics.Endpoints</AssemblyName>
        <RootNamespace>Metrics</RootNamespace>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Protocol\Protocol.csproj" />
      <ProjectReference Include="..\Publisher\Publisher.csproj" />
    </ItemGroup>

</Project>
